# Generated by Django 2.0 on 2017-12-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('quiz', '0002_make_tag_name_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answered',
            field=models.IntegerField(default=0),
        ),
    ]
