# Generated by Django 2.0 on 2017-12-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('quiz', '0004_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
