# Generated by Django 2.0 on 2018-01-04 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('quiz', '0006_questionattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionattempt',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Answer'),
        ),
    ]
