# Generated by Django 2.0 on 2018-01-05 15:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('quiz', '0007_questionattempt_nullable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answered',
        ),
    ]
